### ISSUE TITLE
CI-CD-and-GitHub-Actions

### ISSUE THREAD

**Issue by danielkull** [danielkull/todo-app-with-cypress#6]
# GitHub Action for Todo App

Create a GitHub Action for your Todo App that will start the dev server, run e2e tests and unit tests.

- [x] Create a GitHub Action in the `.github/worflows` folder of your Todo App
- [x] Run your automated tests in the GitHub Action
- [x] #9

> Don't forget to run Cypress with the `run` argument - you can use a separate npm script for that.

> Read more about GitHub Actions here: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

```yml

# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: CI

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      # Run the command to install node deps
      - run: npm ci
      # Run the command to start your dev server followed by the & sign
      - run: npm run devserver &
      # Run the command for the e2e tests
      - run: npm run e2e:ci
      # Run the command for the unit tests
      - run: npm run e2e:ci
```
